// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240711094240_financialMetric")]
    partial class financialMetric
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idusers");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob")
                        .HasColumnName("PasswordSalt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.Deal", b =>
                {
                    b.Property<int>("Deal_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Amortization_type")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Asset_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Availability_fee")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("Availability_period")
                        .HasColumnType("int");

                    b.Property<int?>("Cash_Interest_Period")
                        .HasColumnType("int");

                    b.Property<int?>("Client_Id")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Deal_Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Drawdown")
                        .HasColumnType("int");

                    b.Property<int?>("Entity_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Facility")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("IRR")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool?>("Intercompany_loan")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Interest_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Investment_date")
                        .HasColumnType("date");

                    b.Property<decimal?>("LTV_Entry")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("MOIC")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("Maturity_date")
                        .HasColumnType("date");

                    b.Property<decimal?>("Minimum_multiple")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("NAV")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("Opening_fee")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("Ownership_Id")
                        .HasColumnType("int");

                    b.Property<int?>("PIK_Interest_Period")
                        .HasColumnType("int");

                    b.Property<int?>("Related_fund_id")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Subsector")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Underwriting_IRR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Underwriting_MOIC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Underwriting_NAV")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Deal_Id");

                    b.ToTable("deal", "incus_capital");
                });

            modelBuilder.Entity("API.Entities.Fund", b =>
                {
                    b.Property<int?>("Fund_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Administrator")
                        .HasColumnType("longtext");

                    b.Property<int?>("Bank_account_entity")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Custodian")
                        .HasColumnType("longtext");

                    b.Property<string>("Director_one")
                        .HasColumnType("longtext");

                    b.Property<string>("Director_thre")
                        .HasColumnType("longtext");

                    b.Property<string>("Director_two")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("End_Hp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("End_Ip")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Entity")
                        .HasColumnType("int");

                    b.Property<string>("Fund_name")
                        .HasColumnType("longtext");

                    b.Property<int?>("NIF")
                        .HasColumnType("int");

                    b.Property<string>("Register")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Start_Hp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Start_Ip")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Total_commitment")
                        .HasColumnType("int");

                    b.Property<int?>("VAT_number")
                        .HasColumnType("int");

                    b.HasKey("Fund_Id");

                    b.ToTable("fund", "incus_capital");
                });

            modelBuilder.Entity("API.Entities.Transaction", b =>
                {
                    b.Property<int?>("Transaction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount_Due_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Amount_Due_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Capitalized")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cash_Interest_Accrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cash_Interest_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cash_Interest_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cash_Interest_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Drawdown")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Occurred")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("PIK_Interest_Accrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIK_Interest_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIK_Interest_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIK_Interest_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Principal_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Principal_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Related_Deal_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Repayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Repayment_CashInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Repayment_PIKInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Repayment_Principal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Repayment_UndrawnFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Transaction_Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("Undrawn_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Undrawn_Fee_Interest_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Undrawn_Interest_Accrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Undrawn_Interest_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Undrawn_Interest_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Transaction_Id");

                    b.ToTable("transactions", "incus_capital");
                });
#pragma warning restore 612, 618
        }
    }
}
