// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idusers");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob")
                        .HasColumnName("PasswordSalt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.Cash_Rec", b =>
                {
                    b.Property<int?>("CashRec_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cash_rec_id");

                    b.Property<string>("Account")
                        .HasColumnType("longtext")
                        .HasColumnName("account");

                    b.Property<string>("AccountHolder")
                        .HasColumnType("longtext")
                        .HasColumnName("account_holder");

                    b.Property<string>("Bank")
                        .HasColumnType("longtext")
                        .HasColumnName("bank");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext")
                        .HasColumnName("comments");

                    b.Property<string>("Counterparty")
                        .HasColumnType("longtext")
                        .HasColumnName("counterparty");

                    b.Property<string>("CounterpartyName")
                        .HasColumnType("longtext")
                        .HasColumnName("counterparty_name");

                    b.Property<string>("EntryDate")
                        .HasColumnType("longtext")
                        .HasColumnName("entry_date");

                    b.Property<string>("Error")
                        .HasColumnType("longtext")
                        .HasColumnName("error");

                    b.Property<string>("Fund")
                        .HasColumnType("longtext")
                        .HasColumnName("fund");

                    b.Property<string>("IncludedInLoanTemplate")
                        .HasColumnType("longtext")
                        .HasColumnName("included_in_loan_template");

                    b.Property<string>("LoanTemplate")
                        .HasColumnType("longtext")
                        .HasColumnName("loan_template");

                    b.Property<string>("Project")
                        .HasColumnType("longtext")
                        .HasColumnName("project");

                    b.Property<string>("ProjectExits")
                        .HasColumnType("longtext")
                        .HasColumnName("project_exits");

                    b.Property<string>("SubType")
                        .HasColumnType("longtext")
                        .HasColumnName("subtype");

                    b.Property<string>("TransactionAmount")
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_amount");

                    b.Property<string>("TransactionCurrency")
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_currency");

                    b.Property<string>("TransactionMotivation")
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_motivation");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<string>("TypeIncludedInLoanTemplate")
                        .HasColumnType("longtext")
                        .HasColumnName("type_included_in_loan_template");

                    b.Property<string>("ValueDate")
                        .HasColumnType("longtext")
                        .HasColumnName("value_date");

                    b.HasKey("CashRec_Id");

                    b.ToTable("Cash_Rec");
                });

            modelBuilder.Entity("API.Entities.Deal", b =>
                {
                    b.Property<string>("Deal_Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Acceleration_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Asset_Class")
                        .HasColumnType("longtext");

                    b.Property<int?>("Availability_period")
                        .HasColumnType("int");

                    b.Property<string>("Borrower")
                        .HasColumnType("longtext");

                    b.Property<string>("Capital_Repayment")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CashInterest_End_1st")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CashInterest_End_2nd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CashInterest_End_3rd")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CashInterest_Rate_1st")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashInterest_Rate_2nd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashInterest_Rate_3rd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Client")
                        .HasColumnType("longtext");

                    b.Property<string>("Client_Country_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Country_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Coupon")
                        .HasColumnType("longtext");

                    b.Property<string>("Deal_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Deal_Source")
                        .HasColumnType("longtext");

                    b.Property<string>("Default_Capitalization_Periods")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Default_interest_rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EURIBOR_Interest_Rate")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Exit_fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Extension_Period")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Facility")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("First_Utilization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Grouping")
                        .HasColumnType("longtext");

                    b.Property<string>("Instrument_Dealddbbb")
                        .HasColumnType("longtext");

                    b.Property<string>("Instrument_LoanTemplateddbb")
                        .HasColumnType("longtext");

                    b.Property<string>("Interest_Period")
                        .HasColumnType("longtext");

                    b.Property<string>("Interest_Rate_Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Investment_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lender")
                        .HasColumnType("longtext");

                    b.Property<string>("Loan")
                        .HasColumnType("longtext");

                    b.Property<string>("Loan_Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Maturity_date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Minimum_Multiple")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Opening_fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Origination")
                        .HasColumnType("longtext");

                    b.Property<string>("Others")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PIKInterest_End_1st")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PIKInterest_End_2nd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PIKInterest_End_3rd")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("PIKInterest_Rate_1st")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIKInterest_Rate_2nd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIKInterest_Rate_3rd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PIYCInterest_End_1st")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PIYCInterest_End_2nd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PIYCInterest_End_3rd")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("PIYCInterest_Rate_1st")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIYCInterest_Rate_2nd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIYCInterest_Rate_3rd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Percent_Coinvestor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Percent_Master_Fund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Purchase_Discount_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Related_Fund")
                        .HasColumnType("longtext");

                    b.Property<string>("Repeat_Counterparty")
                        .HasColumnType("longtext");

                    b.Property<string>("Sector")
                        .HasColumnType("longtext");

                    b.Property<string>("Seniority")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Share_Premium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sponsorship")
                        .HasColumnType("longtext");

                    b.Property<string>("Strategy")
                        .HasColumnType("longtext");

                    b.Property<string>("Subsector")
                        .HasColumnType("longtext");

                    b.Property<string>("Thematic_Vs_Opportunistic")
                        .HasColumnType("longtext");

                    b.Property<string>("Theme")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Underwriting_IRR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Underwriting_MOIC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Underwriting_NAV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Undrawn_fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Undrawn_fee_periods")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Year_Base")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Deal_Id");

                    b.ToTable("deal", "incus_capital");
                });

            modelBuilder.Entity("API.Entities.FinancialMetrics", b =>
                {
                    b.Property<int>("Metrics_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("Accrued_Cash_Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Accrued_Pik_Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Accrued_Undrawn_Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Facility")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Interest_Generated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Interest_Payed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nav")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nav_irr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nav_moic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nav_profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total_Collections")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total_Debt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total_Invested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Transaction_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Undrawn_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Metrics_id");

                    b.ToTable("financial_metrics");
                });

            modelBuilder.Entity("API.Entities.Fund", b =>
                {
                    b.Property<int?>("Fund_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Administrator")
                        .HasColumnType("longtext");

                    b.Property<int?>("Bank_account_entity")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Custodian")
                        .HasColumnType("longtext");

                    b.Property<string>("Director_one")
                        .HasColumnType("longtext");

                    b.Property<string>("Director_thre")
                        .HasColumnType("longtext");

                    b.Property<string>("Director_two")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("End_Hp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("End_Ip")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Entity")
                        .HasColumnType("int");

                    b.Property<string>("Fund_name")
                        .HasColumnType("longtext");

                    b.Property<int?>("NIF")
                        .HasColumnType("int");

                    b.Property<string>("Register")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Start_Hp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Start_Ip")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Total_commitment")
                        .HasColumnType("int");

                    b.Property<int?>("VAT_number")
                        .HasColumnType("int");

                    b.HasKey("Fund_Id");

                    b.ToTable("fund", "incus_capital");
                });

            modelBuilder.Entity("API.Entities.Transaction", b =>
                {
                    b.Property<int?>("Transaction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Accrued")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount_Due_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Amount_Due_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Capitalized")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cash_Interest_Accrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cash_Interest_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cash_Interest_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cash_Interest_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Deal_Name")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Drawdown")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Occurred")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("PIK_Interest_Accrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIK_Interest_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIK_Interest_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PIK_Interest_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Principal_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Principal_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Projection")
                        .HasColumnType("int");

                    b.Property<string>("Related_Deal_Id")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Repayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Repayment_CashInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Repayment_PIKInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Repayment_Principal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Repayment_UndrawnFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Transaction_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Undrawn_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Undrawn_Fee_Interest_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Undrawn_Interest_Accrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Undrawn_Interest_BOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Undrawn_Interest_EOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Withrawn_Principal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Transaction_Id");

                    b.ToTable("transactions", "incus_capital");
                });
#pragma warning restore 612, 618
        }
    }
}
